### ISSUE TITLE
TravisCI builds seem to fail due to "Cannot find module 'eslint-config-prettier/@typescript-eslint'"

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1275]
All TravsiCI builds seem to be failing because of the following:

```
$ umi test ./src/components ./src/pages --verbose --maxWorkers=1 --runInBand
✖  error     Error: Cannot find module 'eslint-config-prettier/@typescript-eslint' 
Referenced from: 
    at ModuleResolver.resolve (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config/config-file.js:579:26)
    at configExtends.reduceRight (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config/config-file.js:431:26)
    at Object.loadObject (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config/config-file.js:566:35)
    at new Config (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/config.js:85:46)
    at new CLIEngine (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/eslint/lib/cli-engine.js:466:23)
    at Object.<anonymous> (/home/travis/build/distributed-system-analysis/pbench/web-server/v0.4/node_modules/sylvanas/lib/eslintJs.js:6:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn unit tests failed!
```

**Comment by portante** [comment]
Fixed by #1284.
