### ISSUE TITLE
pre-commit hook for e2e tests failing

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1276]
It seems as though the pre-commit hook has started failing on my RHEL 7.6 box:

```
[pportant@perf48 util-scripts]$ git push --force origin containerized-tools
husky > pre-push (node v8.16.0)

> pbench_dashboard@2.0.0 test:e2e /home/pportant/pbench/web-server/v0.4
> umi test ./src/e2e --verbose

 FAIL  src/e2e/search.e2e.js
  ● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      14 |
      15 | afterAll(() => {
    > 16 |   browser.close();
         |           ^
      17 | });
      18 |
      19 | describe('search page component', () => {

      at Object.close (src/e2e/search.e2e.js:16:11)

 FAIL  src/e2e/controllers.e2e.js
  ● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      14 |
      15 | afterAll(() => {
    > 16 |   browser.close();
         |           ^
      17 | });
      18 |
      19 | describe('controller page component', () => {

      at Object.close (src/e2e/controllers.e2e.js:16:11)

 FAIL  src/e2e/results.e2e.js
  ● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      14 |
      15 | afterAll(() => {
    > 16 |   browser.close();
         |           ^
      17 | });
      18 |
      19 | describe('results page component', () => {

      at Object.close (src/e2e/results.e2e.js:16:11)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        3.384s
Ran all test suites matching /.\/src\/e2e/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pbench_dashboard@2.0.0 test:e2e: `umi test ./src/e2e --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pbench_dashboard@2.0.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pportant/.npm/_logs/2019-07-20T02_06_25_885Z-debug.log
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@github.com:portante/pbench.git'
```

**Comment by portante** [comment]
Even though we have merged #1284, this is still failing in the same was as documented above.

**Comment by gurbirkalsi** [comment]
@portante Can you check if this issue still persists? It seemed to have resolved itself within my environment referencing the latest changes to the master branch. 

Version of node I'm running in my environment:
```bash
➜ node -v
v12.1.0
```

**Comment by gurbirkalsi** [comment]
@Anisha1234 Have you observed this issue within your environment recently as well?

**Comment by portante** [comment]
@gurbirkalsi, I am using node v8.16.1.  If we now require node v12.1.0, is that documented some where, or in the requirements files for NodeJS we keep?

**Comment by portante** [comment]
Still fails the same way with node v12.8.1.

**Comment by gurbirkalsi** [comment]
Hmm, can you please share the error log from the pre-commit hook? I don't believe this is a node version compatibility issue - unfortunately the error log on my environment didn't emit enough information to determine this.

**Comment by portante** [comment]
It is the same error log as reported initially.

**Comment by gurbirkalsi** [comment]
Sorry, I meant the full debug log that was emitted here:

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pportant/.npm/_logs/2019-07-20T02_06_25_885Z-debug.log
```

**Comment by portante** [comment]
Sure, here is the contents of the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:e2e' ]
2 info using npm@6.10.2
3 info using node@v12.8.1
4 verbose run-script [ 'pretest:e2e', 'test:e2e', 'posttest:e2e' ]
5 info lifecycle pbench_dashboard@2.0.0~pretest:e2e: pbench_dashboard@2.0.0
6 info lifecycle pbench_dashboard@2.0.0~test:e2e: pbench_dashboard@2.0.0
7 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: unsafe-perm in lifecycle true
8 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pportant/pbench/web-server/v0.4/node_modules/.bin:/home/pportant/pbench/web-server/v0.4/node_modules/.bin:/home/pportant/pbench/web-server/node_modules/.bin:/home/pportant/pbench/node_modules/.bin:/home/pportant/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/bin:/usr/libexec/git-core:/opt/pbench-agent/util-scripts:/opt/pbench-agent/bench-scripts:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/pportant/.local/bin:/home/pportant/bin
9 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: CWD: /home/pportant/pbench/web-server/v0.4
10 silly lifecycle pbench_dashboard@2.0.0~test:e2e: Args: [ '-c', 'umi test ./src/e2e --verbose' ]
11 silly lifecycle pbench_dashboard@2.0.0~test:e2e: Returned: code: 1  signal: null
12 info lifecycle pbench_dashboard@2.0.0~test:e2e: Failed to exec test:e2e script
13 verbose stack Error: pbench_dashboard@2.0.0 test:e2e: `umi test ./src/e2e --verbose`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pbench_dashboard@2.0.0
15 verbose cwd /home/pportant/pbench/web-server/v0.4
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:e2e"
18 verbose node v12.8.1
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error pbench_dashboard@2.0.0 test:e2e: `umi test ./src/e2e --verbose`
22 error Exit status 1
23 error Failed at the pbench_dashboard@2.0.0 test:e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gurbirkalsi** [comment]
@portante Does deleting the node modules and reinstalling using `yarn` fix this issue?

**Comment by portante** [comment]
Just re-installed all the node modules and it failed the same way. :(

**Comment by Anisha1234** [comment]
@gurbirkalsi @portante it is failing for me as well. my /home/aswain/.npm/_logs/2019-08-22T07_03_29_529Z-debug.log file shows,
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:e2e' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'pretest:e2e', 'test:e2e', 'posttest:e2e' ]
5 info lifecycle pbench_dashboard@2.0.0~pretest:e2e: pbench_dashboard@2.0.0
6 info lifecycle pbench_dashboard@2.0.0~test:e2e: pbench_dashboard@2.0.0
7 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: unsafe-perm in lifecycle true
8 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/aswain/work/pbench/web-server/v0.4/node_modules/.bin:/home/aswain/work/pbench/web-server/v0.4/node_modules/.bin:/home/aswain/work/pbench/web-server/node_modules/.bin:/home/aswain/work/pbench/node_modules/.bin:/home/aswain/work/node_modules/.bin:/home/aswain/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/bin:/usr/libexec/git-core:/home/aswain/.local/bin:/home/aswain/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
9 verbose lifecycle pbench_dashboard@2.0.0~test:e2e: CWD: /home/aswain/work/pbench/web-server/v0.4
10 silly lifecycle pbench_dashboard@2.0.0~test:e2e: Args: [ '-c', 'umi test ./src/e2e --verbose' ]
11 silly lifecycle pbench_dashboard@2.0.0~test:e2e: Returned: code: 1  signal: null
12 info lifecycle pbench_dashboard@2.0.0~test:e2e: Failed to exec test:e2e script
13 verbose stack Error: pbench_dashboard@2.0.0 test:e2e: `umi test ./src/e2e --verbose`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pbench_dashboard@2.0.0
15 verbose cwd /home/aswain/work/pbench/web-server/v0.4
16 verbose Linux 5.2.8-200.fc30.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:e2e"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error pbench_dashboard@2.0.0 test:e2e: `umi test ./src/e2e --verbose`
22 error Exit status 1
23 error Failed at the pbench_dashboard@2.0.0 test:e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```


node version: v10.16.0
There are timeout error in most of the tests
