### ISSUE TITLE
The pbench server should handle connection errors a bit more gracefully

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1556]
The pbench server processes throw really weird errors when they cannot connect to the Elasticsearch instance:
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9471cf2668>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pbench-server/lib/pbench/indexer.py", line 424, in update_templates
    name=name, body=self.templates[name])
  File "/opt/pbench-server/lib/pbench/indexer.py", line 536, in es_put_template
    tmpl = es.indices.get_template(name=name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/client/indices.py", line 549, in get_template
    name), params=params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch1/connection/http_urllib3.py", line 89, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch1.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9471cf2668>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9471cf2668>: Failed to establish a new connection: [Errno 111] Connection refused)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-report-status.py", line 61, in <module>
    report.init_report_template()
  File "/opt/pbench-server/lib/pbench/report.py", line 90, in init_report_template
    self.templates.update_templates(self.es, 'server-reports')
  File "/opt/pbench-server/lib/pbench/indexer.py", line 427, in update_templates
    raise TemplateError(e)
pbench.indexer.TemplateError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9471cf2668>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9471cf2668>: Failed to establish a new connection: [Errno 111] Connection refused)
```

**Comment by portante** [comment]
Consider moving this to [py-es-bulk](https://github.com/distributed-system-analysis/py-es-bulk) when we implement #1755.
