### ISSUE TITLE
pbench-indexer "AssertionError" with "actions_retry_deque" is not empty

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1621]
Saw this error on staging, where the `es_index` action re-try `deque` (Python 3 queue object) is not empty when it should be:

```
2020-04-23T16:09:12.967620 ERROR 1574 139925273302848 pbench-sync-satellite.report post_status 232 -- Failed to post status, name = pbench-sync-satellite, timestamp = 2020-04-23T16:09:02-UTC, doctype = status, file_to_index = /srv/pbench-local/tmp/pbench-sync-satellite.1248/index_mail_contents
Traceback (most recent call last):
  File "/opt/pbench-server/lib/pbench/report.py", line 210, in post_status
    self.es, _es_payload_gen(payload_gen), sys.stderr, self.logger
  File "/opt/pbench-server/lib/pbench/indexer.py", line 857, in es_index
    assert len(actions_retry_deque) == 0
AssertionError
```

**Comment by portante** [comment]
The assertion should be removed and replaced with an error log, that also provides more contextual information.

**Comment by portante** [comment]
Let's consider moving this to https://github.com/distributed-system-analysis/py-es-bulk/ when we change to depend on it (see https://github.com/distributed-system-analysis/pbench/issues/1755).

**Comment by riya-17** [comment]
@portante I think this issue has been taken care of in PR #1626, we can close it.

**Comment by portante** [comment]
PR #1626 does not really allow us to close this issue because it only solves the problem of the error reporting.  The reason the assertion was seen in the first place still needs to be investigated.

**Comment by riya-17** [comment]
@portante "2020-04-23T16:09:12.967620 ERROR 1574 139925273302848 pbench-sync-satellite.report post_status 232 -- Failed to post status, name = pbench-sync-satellite, timestamp = 2020-04-23T16:09:02-UTC, doctype = status, file_to_index = /srv/pbench-local/tmp/pbench-sync-satellite.1248/index_mail_contents" 
what does 232 meant in this line?
