### ISSUE TITLE
Traceback while running audit on satellite

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1672]
```
[pbench@ip-foo pbench-dispatch]$ _PBENCH_SERVER_CONFIG=/opt/pbench-server/lib/config/pbench-server.cfg  flock -n /opt/pbench-server/lib/locks/pbench-audit-server.lock /opt/pbench-server/bin/pbench-audit-server
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-report-status.py", line 10, in <module>
    from pbench.report import Report
  File "/opt/pbench-server/lib/pbench/report.py", line 14, in <module>
    from pbench.indexer import PbenchTemplates, get_es, es_index, _op_type
  File "/opt/pbench-server/lib/pbench/indexer.py", line 27, in <module>
    from urllib3 import Timeout
ModuleNotFoundError: No module named 'urllib3'
```

**Comment by ndokos** [comment]
This was on a RHEL7 system. We expect to get python3 through SCL and do *not* expect to have a python3 outside that environment. However on this system, there was a /usr/bin/python3 installed . That causes the above problem (urrllib3 is installed in the SCL environment but *not* in the global environment.

The solution is to get rid of the python3 package in the global environment.
