### ISSUE TITLE
python setup.py install only works from the git repo clone

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1795]
If I try `python setup.py install` from a copy of the git repo clone (but without the .git subdirectory), I get an exception in pbr:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.7/site-packages/pbr/util.py", line 256, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3.7/site-packages/pbr/packaging.py", line 849, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pbench was given, but was not able to be found.
error in setup command: Error parsing /opt/pbench-server/server-lib/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pbench was given, but was not able to be found.
```

Looking at `pbr/packaging.py:get_version`, it looks for some env variables (`PBR_VERSION` and default `OSLO_PACKAGE_VERSION` - boggles the mind), then it looks at package metadata (a PKG-INFO file or a METADATA file) and then it looks at git (and comes up with a mysterious 0.68.1.dev106 version when there is a .git subdir).

This needs to work without a .git subdir (e.g. when making an RPM). My current workaround is to do a build in the git repo and then slam the resulting PKG-INFO file into the main directory of the copy.

**Comment by ndokos** [comment]
Not sure about the context any longer: I think we were doing a `python setup.py install` from the `pbench-agent` SPEC file and that was failing when run in the main repo clone because I had a worktree subdirectory in that directory - or maybe it was the other way round: running it inside the worktree when the worktree was a subdirectory of the main repo.

Whatever the case might have been, I cannot reproduce it any longer, with or without a `.git` file in the worktree; and also from the main repo with a worktree as a sudbidr. The invocation of the `setup` step in the `pbench-agent` SPEC file works in all cases without errors.

Closing this as non-reproducible. This issue is linked to from PBENCH-316.
