### ISSUE TITLE
pbench-prep-server-shim-002 wants to write things to an old-style logfile

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1877]
Installed current server bits on a clean machine and tried all the cron jobs by hand. `prep-shim` failed with the following error:

```
$ flock -n /opt/pbench-server/lib/locks/pbench-prep-002.lock /opt/pbench-server/bin/pbench-server-prep-shim-002
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 314, in <module>
    status = main(cfg_name)
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 265, in main
    ).open(mode="w") as error_f:
  File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/srv/pbench-local/logs/pbench-server-prep-shim-002/pbench-server-prep-shim-002.error'
```

It succeeds if I create that directory, but why is it even trying to write into that file? Shouldn't it be logging to syslog?

**Comment by riya-17** [comment]
The directory must have been created by the logger. I am unable to understand what leads to this error. This file is used for writing all the errors that were caused in the process. We use logging for logging the success reports.

**Comment by riya-17** [comment]
if I am creating the logger after error file creation(like I have mentioned below) then, I am experiencing the same error.
```
262     with Path(
263         config.LOGSDIR,
264         "pbench-server-prep-shim-002",
265         "pbench-server-prep-shim-002.error",
266     ).open(mode="w") as error_f:
267         qdir, receive_dir = fetch_config_val(config, error_f)
268 
269         if qdir is None and receive_dir is None:
270             return 2
271 
272         logger = get_pbench_logger(_NAME_, config)
```

```
! Traceback (most recent call last):
!   File "/var/tmp/pbench-test-server/test-5.2/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 318, in <module>
!     status = main(cfg_name)
!   File "/var/tmp/pbench-test-server/test-5.2/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 266, in main
!     ).open(mode="w") as error_f:
!   File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
!     opener=self._opener)
!   File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
!     return self._accessor.open(self, flags, mode)
!   File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
!     return strfunc(str(pathobj), *args)
! FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/pbench-test-server/test-5.2/pbench-local/logs/pbench-server-prep-shim-002/pbench-server-prep-shim-002.error'
```

**Comment by riya-17** [comment]
logger.py seems to get changed after this commit https://github.com/distributed-system-analysis/pbench/commit/4a06bd46b5249c60aa74a0a917a500ce8e3edc1f.

found the issue: earlier we used to create caller directories with whatever logging we use (file  or Syslog any) while now we only create it when we use fileHandler
