### ISSUE TITLE
The pbench-agent fails to install on RHEL 7/CentOS 7

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2245]
The pbench-agent no longer installs on RHEL 7 / CentOS 7 due to the following errors:

```
# yum install pbench-agent
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package pbench-agent.noarch 0:0.71.0-158g2624b973d will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================
 Package                              Arch                           Version                                       Repository                                         Size
===========================================================================================================================================================================
Installing:
 pbench-agent                         noarch                         0.71.0-158g2624b973d                          copr-pbench-test-portante                         354 k

Transaction Summary
===========================================================================================================================================================================
Install  1 Package

Total download size: 354 k
Installed size: 1.4 M
Is this ok [y/d/N]: y
Downloading packages:
pbench-agent-0.71.0-158g2624b973d.noarch.rpm                                                                                                        | 354 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : pbench-agent-0.71.0-158g2624b973d.noarch                                                                                                                1/1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xzhn6hb8/cryptography/
  Verifying  : pbench-agent-0.71.0-158g2624b973d.noarch                                                                                                                1/1

Installed:
  pbench-agent.noarch 0:0.71.0-158g2624b973d

Complete!
```

The `WARNING` above is not a problem, but the `failed with error code 1` line is a problem, and should have killed the installation.

You can see the full error reported in `/opt/pbench-agent/pip3-install.log`:

```
Collecting cryptography (from ansible-base<2.11,>=2.10.8->ansible->-r /opt/pbench-agent/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3f35dz43/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

The fix seems to be to install the latest version of `pip`, see https://github.com/Azure/azure-cli/issues/16858#issuecomment-778360285

**Comment by portante** [comment]
This failed on RHEL 7.8 systems.  Looking to see if this is resolved by RHEL 7.9 in some way.
