### ISSUE TITLE
`pbench-trafficgen --traffic-generator=trex-txrx-profile` fails with `JSONDecodeError`

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2265]
pbench-trafficgen v0.69.7:

```
$ pbench-trafficgen --config=Test --devices d8:00.0,d8:00.1 --skip-git-pull  --traffic-generator=trex-txrx-profile

[2021-04-14 12:32:42.131906][BSO] EXCEPTION: Traceback (most recent call last):
[2021-04-14 12:32:42.131906][BSO]   File "/opt/trafficgen/trex_tg_lib.py", line 594, in load_traffic_profile
[2021-04-14 12:32:42.131906][BSO]     profile = json.load(traffic_profile_fp)
[2021-04-14 12:32:42.131906][BSO]   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
[2021-04-14 12:32:42.131906][BSO]     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
[2021-04-14 12:32:42.131906][BSO]   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
[2021-04-14 12:32:42.131906][BSO]     return _default_decoder.decode(s)
[2021-04-14 12:32:42.131906][BSO]   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
[2021-04-14 12:32:42.131906][BSO]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2021-04-14 12:32:42.131906][BSO]   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
[2021-04-14 12:32:42.131906][BSO]     raise JSONDecodeError("Expecting value", s, err.value) from None
[2021-04-14 12:32:42.131906][BSO] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by portante** [comment]
@aokuliar-rh, since `--skip-git-pull` is used, can you find out what version of `/opt/trafficgen` was pulled previously?

**Comment by portante** [comment]
Recent testing showed this problem with this commit: https://github.com/atheurer/trafficgen/commit/6cbf23632367e92b0ba4acbca9ecfd06919dd18f.
