### ISSUE TITLE
pbench-list-tools ends with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2345]
pbench-agent-0.71.0-185g5527f23f1.noarch

1) run
```
pbench-register-tool-trigger --start-trigger='START TRIGGER' --stop-trigger='STOP TRIGGER' --group=another 
```
2) run
```
pbench-list-tools -n perf
```
```
Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-list-tools", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 135, in main
    status = ListTools(ctxt).execute()
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 61, in execute
    if self.context.name in self.tools(path):
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/base.py", line 19, in tools
    for p in path.iterdir()
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/base.py", line 18, in <listcomp>
    p.name
  File "/usr/lib64/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
NotADirectoryError: [Errno 20] Not a directory: '/var/lib/pbench-agent/tools-v1-another/__trigger__'
```

**Comment by ndokos** [comment]
There are two problems here: `pbench-register-tool-trigger --start-trigger='START TRIGGER' --stop-trigger='STOP TRIGGER' --group=another ` requires the group `another` to exist already; that was not the case in 0.69.9: the group was stored as part of the trigger speciifcation. Then there is the exception.
