### ISSUE TITLE
pbench-list-tools -n crashes with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2464]
pbench-agent-0.71.0-1g8e186271c.noarch
# pbench-list-tools 
another: brusic1.slevarna.tpb.lab.eng.brq.redhat.com ['blktrace', 'iostat', 'mpstat', 'perf', 'pidstat', 'proc-interrupts', 'proc-vmstat', 'sar', 'turbostat']
default: brusic1.slevarna.tpb.lab.eng.brq.redhat.com ['blktrace', 'iostat', 'mpstat', 'perf', 'pidstat', 'proc-interrupts', 'proc-vmstat', 'sar', 'turbostat']

pbench-list-tools -n iostat
Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-list-tools", line 10, in <module>
    sys.exit(main())
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 135, in main
    status = ListTools(ctxt).execute()
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 61, in execute
    if self.context.name in self.tools(path):
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/base.py", line 19, in tools
    for p in path.iterdir()
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/base.py", line 18, in <listcomp>
    p.name
  File "/usr/lib64/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
NotADirectoryError: [Errno 20] Not a directory: '/var/lib/pbench-agent/tools-v1-another/__trigger__'

**Comment by ndokos** [comment]
PR #2467 will fix this.
