### ISSUE TITLE
pbench-list-tools -o crashes with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2465]
pbench-agent-0.71.0-1g8e186271c.noarch

# pbench-list-tools 
another: brusic1.slevarna.tpb.lab.eng.brq.redhat.com ['blktrace', 'iostat', 'mpstat', 'perf', 'pidstat', 'proc-interrupts', 'proc-vmstat', 'sar', 'turbostat']
default: brusic1.slevarna.tpb.lab.eng.brq.redhat.com ['blktrace', 'iostat', 'mpstat', 'perf', 'pidstat', 'proc-interrupts', 'proc-vmstat', 'sar', 'turbostat']

# pbench-list-tools -o
Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-list-tools", line 10, in <module>
    sys.exit(main())
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/pbench-agent/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 135, in main
    status = ListTools(ctxt).execute()
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 42, in execute
    p.read_text() for p in self.tools(path)
  File "/opt/pbench-agent/lib/pbench/cli/agent/commands/tools/list.py", line 42, in <listcomp>
    p.read_text() for p in self.tools(path)
AttributeError: 'str' object has no attribute 'read_text'

**Comment by ndokos** [comment]
PR #2467 will fix this - when it lands.
