### ISSUE TITLE
[pbench-fio] Connectivity errors and missing/corrupted metadata

### ISSUE THREAD

**Issue by spetrovi** [distributed-system-analysis/pbench#2503]
**pbench version: 0.71.0**

Hey, I encountered weird problems while testing pbench-fio. After every subtest, I get a bunch of these connectivity errors:

`running fio job: /var/lib/pbench-agent/fio__2021.10.19T09.23.30/1-read-4KiB/fio.job (sample1)
Traceback (most recent call last):
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-tool-meister-client", line 92, in <module>
    status = main(sys.argv)
  File "/opt/pbench-agent/util-scripts/pbench-tool-meister-client", line 84, in main
    logger=logger,
  File "/opt/pbench-agent/lib/pbench/agent/tool_meister_client.py", line 121, in __enter__
    self.redis_server, self.to_client_channel
  File "/opt/pbench-agent/lib/pbench/agent/redis.py", line 50, in __init__
    self._pubsub.subscribe(channel_name)
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/client.py", line 3468, in execute_command
    self.shard_hint
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:17001. Connection refused.`

This confuses me, because I don't expect pbench-fio to do anything connectivity related.
Anyway, I just thought its a bunch of useless warnings and the results will be fine, but when I try to either make a tarball or copy results to pbench server, it fails with following error:

`[error][2021-10-18T15:18:10.350958328] The run in directory /var/lib/pbench-agent/fio__2021.10.18T11.17.21 has an unexpected metadata name, "" - skipping`

So there is probably some actual problem going on, it seems the 'metadata name', whatever it is, is empty and therefore pbench skips it.

I don't know how to proceed, any insights?

**Comment by portante** [comment]
Thanks for sharing the command history privately.

What we really need in the `/var/lib/pbench-agent/fio__2021.10.19T09.23.30` directory and the contents of the `/var/lib/pbench-agent/pbench.log` file.

**Comment by portante** [comment]
The second error, `has an unexpected metadata name`, indicates that the name the directory, `fio__2021.10.18T11.17.21`, does not match what is stored in the `metadata.log` file in that directory.

That usually indicates that somebody has either changed the name of the directory, or changed the contents of its `metadata.log` file.
