### ISSUE TITLE
duplicate key value violates unique constraint "templates_name_key"

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2580]
```
File "/opt/pbench-server/lib/pbench/server/database/models/template.py", line 198, in add  Database.db_session.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "templates_name_key"
DETAIL:  Key (name)=(iostat) already exists.
```
My best first guess is that this might be related to the startup lag Webb's seen between the Pbench container and the Postgres container within his pod. Specifically, I wonder if we we might be misinterpreting a "not ready" failure for "doesn't exist" and proceeding to insert a "new" row that's not really new.

We should investigate and make sure our error handling is tighter. For example, this might be something like an `except Exception` that really ought to isolate SQLAlchemy "DB connection" errors and treat them differently (for example, re-raise).

Addressing the startup sequencing in the pod might also be nice, but we can't rely on our backend databases always being in sync and operational, so we need our code to be robust against connection errors.

**Comment by webbnh** [comment]
After a small amount of contemplation, I've become convinced that this is due to a race condition between two Server-side tools running concurrently.  It only occurs at the start of a pod and doesn't recur, and the message may show up once, twice, or not at all.

Full traceback of a single-occurrence case:
```
Traceback (most recent call last):
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "templates_name_key"
DETAIL:  Key (name)=(iostat) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 367, in <module>
    status = main(cfg_name)
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 355, in main
    report = Report(config, _NAME_)
  File "/opt/pbench-server/lib/pbench/server/report.py", line 98, in __init__
    self.config.BINDIR, self.idx_prefix, self.logger
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 622, in __init__
    self.resolve()
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 640, in resolve
    template.resolve()
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 485, in resolve
    template.add()
  File "/opt/pbench-server/lib/pbench/server/database/models/template.py", line 201, in add
    raise self._decode(e)
  File "/opt/pbench-server/lib/pbench/server/database/models/template.py", line 198, in add
    Database.db_session.commit()
  File "<string>", line 2, in commit
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
    self._flush(objects)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3485, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3445, in _flush
    flush_context.execute()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 249, in save_obj
    insert,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1224, in _emit_insert_statements
    execution_options=execution_options,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "templates_name_key"
DETAIL:  Key (name)=(iostat) already exists.

[SQL: INSERT INTO templates (name, idxname, template_name, file, mtime, template_pattern, index_template, settings, mappings, version) VALUES (%(name)s, %(idxname)s, %(template_name)s, %(file)s, %(mtime)s, %(template_pattern)s, %(index_template)s, %(settings)s, %(mappings)s, %(version)s) RETURNING templates.id])
[parameters: {'name': 'iostat', 'idxname': 'tool-data-iostat', 'template_name': 'container-pbench.v4.tool-data-iostat', 'file': '/opt/pbench-server/lib/mappings/tool-data-frag-iostat.json', 'mtime': datetime.datetime(2021, 8, 20, 16, 28, 57), 'template_pattern': 'container-pbench.v4.tool-data-iostat.*', 'index_template': '{prefix}.v{version}.{idxname}.{year}-{month}-{day}', 'settings': '{"analysis": {"analyzer": {"comma_analyzer": {"tokenizer": "comma_tokenizer"}}, "tokenizer": {"comma_tokenizer": {"type": "pattern", "pattern": ","}}}, "index": {"query": {"default_field": "@metadata.experiment"}}}', 'mappings': '{"_source": {"enabled": true}, "date_detection": false, "properties": {"@timestamp": {"type": "date"}, "@timestamp_original": {"type": "text"}, "@gen ... (1001 characters truncated) ... ": {"type": "float"}}}}}, "authorization": {"properties": {"owner": {"type": "keyword"}, "access": {"type": "keyword"}}}}, "_meta": {"version": "4"}}', 'version': '4'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by webbnh** [comment]
My most recent restart produced messages from both `pbench-server-prep-shim-002.py` and `pbench-index.py`.  Below is the traceback from `pbench-index.py`:
```
Traceback (most recent call last):
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "templates_name_key"
DETAIL:  Key (name)=(prometheus-metrics) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-index.py", line 233, in <module>
    status = main(parsed, run_name)
  File "/opt/pbench-server/bin/pbench-index.py", line 116, in main
    idxctx = IdxContext(options, name, config, logger, _dbg=_DEBUG)
  File "/opt/pbench-server/lib/pbench/server/indexer.py", line 4084, in __init__
    _dbg=_dbg,
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 622, in __init__
    self.resolve()
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 640, in resolve
    template.resolve()
  File "/opt/pbench-server/lib/pbench/server/templates.py", line 485, in resolve
    template.add()
  File "/opt/pbench-server/lib/pbench/server/database/models/template.py", line 201, in add
    raise self._decode(e)
  File "/opt/pbench-server/lib/pbench/server/database/models/template.py", line 198, in add
    Database.db_session.commit()
  File "<string>", line 2, in commit
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
    self._flush(objects)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3485, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3445, in _flush
    flush_context.execute()
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 249, in save_obj
    insert,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1224, in _emit_insert_statements
    execution_options=execution_options,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/pbench/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "templates_name_key"
DETAIL:  Key (name)=(prometheus-metrics) already exists.

[SQL: INSERT INTO templates (name, idxname, template_name, file, mtime, template_pattern, index_template, settings, mappings, version) VALUES (%(name)s, %(idxname)s, %(template_name)s, %(file)s, %(mtime)s, %(template_pattern)s, %(index_template)s, %(settings)s, %(mappings)s, %(version)s) RETURNING templates.id]
[parameters: {'name': 'prometheus-metrics', 'idxname': 'tool-data-prometheus-metrics', 'template_name': 'container-pbench.v4.tool-data-prometheus-metrics', 'file': '/opt/pbench-server/lib/mappings/tool-data-frag-prometheus-metrics.json', 'mtime': datetime.datetime(2021, 8, 20, 16, 28, 57), 'template_pattern': 'container-pbench.v4.tool-data-prometheus-metrics.*', 'index_template': '{prefix}.v{version}.{idxname}.{year}-{month}-{day}', 'settings': '{"analysis": {"analyzer": {"comma_analyzer": {"tokenizer": "comma_tokenizer"}}, "tokenizer": {"comma_tokenizer": {"type": "pattern", "pattern": ","}}}, "index": {"query": {"default_field": "@metadata.experiment"}}}', 'mappings': '{"_source": {"enabled": true}, "date_detection": false, "properties": {"@timestamp": {"type": "date"}, "@timestamp_original": {"type": "text"}, "@gen ... (1936 characters truncated) ... ": {"type": "keyword"}}}, "authorization": {"properties": {"owner": {"type": "keyword"}, "access": {"type": "keyword"}}}}, "_meta": {"version": "4"}}', 'vers
ion': '4'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by dbutenhof** [comment]
I looked at the code, and I don't see an obvious "leak" of a SQL error, so I suspect that Webb's guess is correct and we're just seeing a race between two or more components all trying to persist a template at the same time after seeing it doesn't yet exist. (In theory we could see the same thing if we ever dynamically updated a template version on the fly, but otherwise this is a startup thing.)

We can either add synchronization to manage this, or simply make sure we pre-load the database before starting cron and the server.

**Comment by webbnh** [comment]
Another possibility, for a "cosmetic fix", would be to stagger the start times of the respective jobs which are hitting this issue, so that they don't collide so consistently.  (Not that we're interested in keeping the cron-based model over a microservices/message-passing approach, but having all of the various jobs starting at exactly the same time after each interval partly defeats the utility of separating them into different jobs (thinking mostly of the unpack tarballs jobs, but moving the others out of each others' way might be good, too).)

**Comment by portante** [comment]
This work was completed by PR #3100.
