### ISSUE TITLE
When no tools are registered, TM should not try to connect to the Redis server

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#2603]
When there are no tools registered on the machine, the tool meister still tries to connect to the redis server (which wouldn't have any active channels because no tools are registered). This creates a loop where the TM continuously tries to connect to redis at a regular interval. This results in the following error:

```
Traceback (most recent call last):
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 607, in connect
    sock = self._connect()
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 671, in _connect
    raise err
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 659, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pbench-agent/util-scripts/pbench-tool-meister-client", line 92, in <module>
    status = main(sys.argv)
  File "/opt/pbench-agent/util-scripts/pbench-tool-meister-client", line 84, in main
    logger=logger,
  File "/opt/pbench-agent/lib/pbench/agent/tool_meister_client.py", line 121, in __enter__
    self.redis_server, self.to_client_channel
  File "/opt/pbench-agent/lib/pbench/agent/redis.py", line 50, in __init__
    self._pubsub.subscribe(channel_name)
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/client.py", line 1527, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/client.py", line 1369, in execute_command
    "pubsub", self.shard_hint
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 1311, in get_connection
    connection.connect()
  File "/opt/pbench-agent/lib/python3.6/site-packages/redis/connection.py", line 611, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:17001. Connection refused.
test sample 1 of 5
client[127.0.0.1]protocol[tcp]test[stream]instances[2]size[131072] <-> server[127.0.0.1]
```
steps to reproduce: 
```
pbench-clear-tools
pbench-uperf --test-types=stream --message-sizes=131072 --runtime=30  --protocols=tcp --instances=2
```

We should consider adding a check for the registered tools in TM and condition that for connecting to the redis server.

**Comment by npalaska** [comment]
Closing this as its been already addressed in PR #2773
