### ISSUE TITLE
`pbench-verify-backup-tarballs` -- `AttributeError: 'S3Connector' object has no attribute 's3client'`

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#3127]
```
2022-12-21T05:53:01.780274 ERROR 990 140524052650880 pbench-verify-backup-tarballs pbench-verify-backup-tarballs sanity_check 268 -- Bucket: None does not exist or you have no access
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-verify-backup-tarballs", line 266, in sanity_check
    s3_obj.head_bucket(Bucket=s3_obj.bucket_name)
  File "/opt/pbench-server/lib/pbench/server/s3backup/__init__.py", line 202, in head_bucket
    return self.connector.head_bucket(Bucket=Bucket)
  File "/opt/pbench-server/lib/pbench/server/s3backup/__init__.py", line 328, in head_bucket
    return self.s3client.head_bucket(Bucket=Bucket)#012AttributeError: 'S3Connector' object has no attribute 's3client'
```

**Comment by portante** [comment]
Fixed by #3175.
