### ISSUE TITLE
IOError: [Errno 2] No such file or directory :  fio_clat_hist.*.log*

### ISSUE THREAD

**Issue by ksingh7** [distributed-system-analysis/pbench#812]
With a server , pbench/pbench-fio setp and default job file ``/opt/pbench-agent/bench-scripts/templates/fio.job`` getting this error

```
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server2/fio_clat_hist.*.log*'
```
I am not sure if i am missing something related to latency thingi.

Full Logs Below : 

```
[root@admin ~]# /opt/pbench-agent/bench-scripts/pbench-fio  --samples=1 -t write,read -b 4,16 --client-file=host.list --targets=/mnt/block1/foo
pbench-fio: package version is missing in config file
verifying clients have fio installed
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
/opt/pbench-agent/bench-scripts/pbench-fio: line 22: /dev/tty: No such device or address
Collecting system information
The following jobfile was created: /var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/fio.job
[global]
bs=4k
runtime=30
ioengine=libaio
iodepth=32
direct=1
sync=0
time_based=1
clocksource=gettimeofday
ramp_time=5
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
log_avg_msec=1000
write_hist_log=fio
log_hist_msec=10000

[job-/mnt/block1/foo]
filename=/mnt/block1/foo
rw=write
size=4096M

running fio job: /var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/fio.job
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Warning: ALREADY_ENABLED: '8765:tcp' already in 'public'
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server2/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server3/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server4/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server5/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server6/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server7/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server8/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server9/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server10/fio_clat_hist.*.log*'
Chart Type: xy
Traceback (most recent call last):
  File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
    main(p.parse_args())
  File "/usr/local/bin/fiologparser_hist.py", line 284, in main
    with open(ctx.FILE[0], 'r') as fp:
IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2018.04.27T08.14.51/1-write-4KiB/sample1/clients/server11/fio_clat_hist.*.log*'
Chart Type: xy
fio job complete
```

**Comment by ksingh7** [comment]
@bengland2  @wilkins11  @ndokos  any thoughts on what i could be missing.

**Comment by bengland2** [comment]
@ksingh7 could you verify that you have fio histogram logs?  It appears that it did not find them in your result directory.  One possible reason for this: your current histogram logging interval is 10 seconds but you only run the test for 30.  In theory, there should be histogram logs being generated, but perhaps the test exited early?  If you could post the entire pbench-fio results directory tree, we could look at it.

**Comment by portante** [comment]
Insufficient information provided to debug at the time, and it looks like it is possibly a user error.
