### ISSUE TITLE
proc-vmstat timestamps are floating point numbers 

### ISSUE THREAD

**Issue by mbruzek** [distributed-system-analysis/pbench#825]
While working on an indexer for the **proc-vmstat** tool I noticed an error testing the index-pbench parsing. It seems the timestamps for proc-vmstat are floating point numbers and the code takes an issue with that. 
```
$ make vmstat               
TMPDIR=tmp PYTHONPATH=../lib:$PYTHONPATH ./index-pbench  --config=tmp/pbench-index.cfg tmp/pbench-user-benchmark_mbruzek-test-1_2018.04.09T22.34.17.tar.xz
Other error invalid literal for int() with base 10: '1523313261391.92'
Traceback (most recent call last):                                                               
  File "./index-pbench", line 1755, in main     
    res = es_index(es, actions)                 
  File "./index-pbench", line 261, in es_index   
    all_actions = list(actions)                                                                  
  File "./index-pbench", line 1612, in make_all_actions
    for action in mk_tool_data_actions(ptb, options, INDEX_PREFIX):
  File "./index-pbench", line 1081, in mk_tool_data_actions
    for source in asource:                      
  File "./index-pbench", line 839, in _make_source_unified                                       
    first = int(first)/1000                     
ValueError: invalid literal for int() with base 10: '1523313261391.92'       
                                                                                          
make: *** [Makefile:8: vmstat] Error 12
```
It seems that all proc-vmstat files have a floating point timestamps: 
```
$ head tmp/pbench-user-benchmark_mbruzek-test-1_2018.04.09T22.34.17/1/reference-result/tools-default/redrum/proc-vmstat/csv/proc-vmstat_compact_delta_sec.csv
timestamp_ms,daemon_free_scanned,daemon_migrate_scanned,daemon_wake,fail,free_scanned,isolated,migrate_scanned,stall,success
1523313261391.92,0,0,0,0,0,0,0,0,0              
1523313264396.56,0,0,0,0,0,0,0,0,0
1523313267399.38,0,0,0,0,0,0,0,0,0
```
All CSV files seem to have this floating point number.

@ndokos suggested it might be an omission in the postprocessing part of the proc-vmstat code.

**Comment by mbruzek** [comment]
Working on this I came to the realization that the string does not need to be converted to an int. A work around was to use the float instead. 
```
            # Create the base document per identifier; the timestamp is taken
            # from the "first" timestamp, converted to a floating point
            # seconds value, and then formatted as a string.
            first = float(first)/1000
```
