### ISSUE TITLE
Errors indexing prometheus data - failure to parse "code" "<error>"

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#920]
Found the following errors when indexing prometheus data:

```
[2018-09-06 18:13:11,068][DEBUG       ][action.bulk              ] [brady-gprfs003] [dsa.pbench.tool-data-prometheus-metrics.2018-09-06][1] failed to execute bulk item (index) index {[dsa.pbench.tool-data-prometheus-metrics.2018-09-06][pbench-tool-data-prometheus-metrics][fed7ee3c51e94bc249988e442c1af44e], source[{"@timestamp": "2018-09-06T17:54:52.000000", "labels": {"code": "<error>", "host": "lb-0.scale-ci.example.com:8443", "method": "POST"}, "metric": "rest_client_requests_total", "type": "COUNTER", "value": 2, "@metadata": {"runtstamp": "2018-09-06T17:38:23.085615026", "runid": "7da029838bf9e342f8a00e7bd4253021", "experiment": "uperf_node-to-node_UDP_2018.09.06T17.38.15", "iteration": "udp_rr-16384B-1i", "iterseqno": "6", "sample": "sample3", "host": "master-0", "toolgroup": "default"}}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [labels.code]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:465)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:418)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "<error>"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:440)
        at java.lang.Long.parseLong(Long.java:482)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
        at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:288)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
        ... 15 more
```

**Comment by portante** [comment]
@chaitanyaenr, any further work on this?  If not, we'll just close and ignore this if it is not really a concern.

**Comment by chaitanyaenr** [comment]
@portante can we modify the milestone to v0.55 please?

**Comment by portante** [comment]
We are no longer going to handle prometheus data directly, but only through the Prometheus data collectors which gathers the entire Prometheus database for the named exporters (`node_exporter`, `dcgm`).
